POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"Esto es una nueva vida",
    "important": true
}
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{

}
